# Generated by Django 6.0.4 on 2026-06-04 00:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('placa', models.CharField(max_length=10, verbose_name='Placa')),
                ('chassi', models.CharField(blank=True, max_length=17, verbose_name='Chassi')),
                ('cliente', models.CharField(max_length=200, verbose_name='Cliente')),
                ('telefone_contato', models.CharField(blank=True, max_length=20, verbose_name='Telefone de Contato')),
                ('data_ocorrencia', models.DateField(verbose_name='Data da Ocorrência')),
                ('descricao', models.TextField(verbose_name='Descrição da Avaria')),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Em Andamento', 'Em Andamento'), ('Aguardando Peças', 'Aguardando Peças'), ('Concluido', 'Concluído'), ('Recusado', 'Recusado')], default='Aberto', max_length=30, verbose_name='Status')),
                ('documento_anexo', models.FileField(blank=True, null=True, upload_to='sinistros/anexos/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Documento Anexo')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sinistros_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Sinistro',
                'verbose_name_plural': 'Sinistros',
                'ordering': ['-criado_em'],
            },
        ),
    ]
