# Generated by Django 6.0.4 on 2026-06-04 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoVigente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('versao', models.CharField(max_length=20)),
                ('conteudo', models.TextField()),
                ('vigente', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Termo Vigente',
                'verbose_name_plural': 'Termos Vigentes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoTitular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('exclusao', 'Exclusão de Dados'), ('portabilidade', 'Portabilidade de Dados'), ('retificacao', 'Retificação de Dados'), ('oposicao', 'Oposição ao Tratamento')], max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('recusada', 'Recusada')], default='pendente', max_length=20)),
                ('justificativa', models.TextField(blank=True)),
                ('resposta', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_lgpd', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação do Titular',
                'verbose_name_plural': 'Solicitações do Titular',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ConsentimentoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceito_em', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimentos', to=settings.AUTH_USER_MODEL)),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lgpd.termovigente')),
            ],
            options={
                'verbose_name': 'Consentimento',
                'verbose_name_plural': 'Consentimentos',
                'ordering': ['-aceito_em'],
            },
        ),
    ]
