# Generated by Django 6.0.4 on 2026-06-04 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_falhou', 'Tentativa de Login Falhou'), ('alteracao', 'Alteração de Dados'), ('exclusao', 'Exclusão'), ('acesso_negado', 'Acesso Negado'), ('exportacao', 'Exportação de Dados'), ('solicitacao_lgpd', 'Solicitação LGPD'), ('outro', 'Outro')], max_length=30)),
                ('descricao', models.TextField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('caminho', models.CharField(blank=True, max_length=500)),
                ('objeto_tipo', models.CharField(blank=True, max_length=100)),
                ('objeto_id', models.CharField(blank=True, max_length=50)),
                ('dados_extras', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Auditoria',
                'verbose_name_plural': 'Eventos de Auditoria',
                'ordering': ['-criado_em'],
            },
        ),
    ]
